config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :profiles
  end
  resources :profiles
  resources :tags
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImagesUploader
	belongs_to :user
  has_and_belongs_to_many :tags
  after_save :update_tags_based_on_elements
  default_scope { order(created_at: :desc) }

  def get_elements_array
    elements = Array.new
    if ev = self.Event
      elements.push("Event:"+ev)
    end
    if pl = self.Place
      elements.push("Place:"+pl)
    end
    if tags_texts = self.tags_text_split
      elements += tags_texts
    end
    return elements
  end

  def update_tags_based_on_elements
    elements = get_elements_array

    # TagになっているElementを削除
    # Elementに含まれないTagを削除
    self.tags.all.each do |tag|
      if elements.include?(tag.name)
        elements.delete(tag.name)
      else
        tag.destroy!
      end
    end
    # 残ったElementをTagにする
    elements.each do |ele|
      change_element_to_tags ele
    end
  end

  # def change_event_to_tags_table
  #   if ev = self.Event
  #     change_element_to_tags ev
  #   end
  # end

  # def change_place_to_tags_table
  #   if pl = self.Place
  #     change_element_to_tags pl
  #   end
  # end

  # def change_tags_text_to_tags_table
  #   if tags_texts = self.tags_text_split
  #     tags_texts.each do |tag_text|
  #       change_element_to_tags tag_text
  #     end
  #   end
  # end

  def change_element_to_tags(el)
    if el
      # タグがすでに存在する場合
      if t = Tag.find_by(name: el)
        # 該当タグがつけられていない場合
        if !self.tags.include?(t)
          self.tags << t
        end
      # タグが存在しない場合
      else
        t = Tag.create(name: el, user_id: self.user.id)
        self.tags << t
      end
    end
  end

  def tags_text_split
    # TODO: 全角スペース
    if self.tags_text
      self.tags_text.split
    else
      nil
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @user = current_user
    @profiles = current_user.profiles.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @user = current_user
    @profile = @user.profiles.new
  end

  # POST /profiles
  # POST /profiles.json
  def create

    @user = current_user
    @profile = @user.profiles.build(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profiles_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :image, :Event, :Place, :tags_text, :memo)
    end

    def correct_user
      @profile = current_user.profiles.find_by(id: params[:id])
      redirect_to root_url if @profile.nil?
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, :氏名 %>
    <%= form.text_field :name, id: :profile_name %>
  </div>

  <div class="field">
    <%= form.label :image, :画像%>
    <%= form.file_field :image, id: :profile_image %>
  </div>

  <div class="field">
    <%= form.label :Event, :イベント %>
    <%= form.text_field :Event, id: :profile_Event %>
  </div>

  <div class="field">
    <%= form.label :Place, :位置情報 %>
    <%= form.text_field :Place, id: :profile_Place %>
  </div>

  <div class="field">
    <%= form.label :tags_text, :タグ %>
    <%= form.text_field :tags_text, id: :profile_tags_text %>
  </div>

  <div class="field">
    <%= form.label :memo, :メモ %>
    <%= form.text_field :memo, id: :profile_memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div class="item">
  <% if !profile.image.file.nil? %>
    <div><%= link_to image_tag( profile.image.to_s ,:size => '200x260'), profile %></div>
  <% else %>
    <div><%= link_to image_tag( 'default_kiminonaha_0.png' ,:size => '200x260'), profile %></div>
  <% end %>
  <div><%= link_to profile.name, profile %></div>
  <div><%= profile.memo %></div>
  <% profile.tags.all.each do |tag| %>
    <%= link_to tag.name, tag, class: "badge badge-info" %>
  <% end %>
  <div><%= link_to '編集', edit_profile_path(profile), class: "btn btn-sm btn-primary" %></div>
  <div><%= link_to '項目削除', profile, class: "btn btn-sm btn-secondary", method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>

app/views/profiles/edit.html.erb
<div class="font_size">
<h1>プロフィール編集</h1>

<%= render 'form', profile: @profile %>

<%= link_to '項目のページへ', @profile %> |
<%= link_to 'マイページへ', profiles_path %>

</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="font_size">
<h1><%= @user.name%>さん のマイページ</h1>
あなたの知人が表示されます<br>
<%= link_to '新規項目作成', new_profile_path, class: "btn btn-primary text-white"%>

<div class="grid">
  <%= render @profiles %>
</div>

<br>

app/views/profiles/new.html.erb
<div class="font_size">
<h1>あなたの新しい知人について教えてください</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'マイページへ', profiles_path %>

</div>

app/views/profiles/show.html.erb
<div class="font_size">
<p id="notice"><%= notice %></p>

<p>
  <strong>画像:</strong>
  <%= image_tag @profile.image.to_s, size: '200x260' %>
</p>

<p>
  <strong>氏名:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>イベント:</strong>
  <%= @profile.Event %>
</p>

<p>
  <strong>位置情報:</strong>
  <%= @profile.Place %>
</p>

<p>
  <strong>タグ:</strong>
  <%= @profile.tags_text %>
</p>

<p>
  <strong>memo:</strong>
  <%= @profile.memo %>
</p>

<%= link_to '編集', edit_profile_path(@profile) %> |
<%= link_to 'マイページへ', profiles_path %>

</div>