config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :profiles
  end
  resources :profiles
  resources :tags
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>君の名は！</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <!-- Header -->
    <nav id="header" class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <%= link_to 'Kiminonaha', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if logged_in? %>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Help', about_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to 'タグ', tags_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', profiles_path, class: "nav-link" %>
            </li>
            <span class="navbar-text">
              Logged in as <%= current_user.name %>
            </span>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, class: "btn btn-outline-secondary", method: 'delete' %>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path, class: "btn btn-outline-secondary" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', signup_path, class: "btn btn-outline-secondary" %>
            </li>
        <% end %>
        </ul>
      </div>
    </nav>

    <!-- Main -->
    <div id="main" class="container">
      <%= yield %>
    </div>

    <!-- Footer -->
    <footer id="footer" class="footer container">
      <p>
      <a href="https://github.com/enpitut2018/kiminonaha">
        View on GitHub
      </a>
      </p>
    </footer>


    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>